### ISSUE TITLE
Getting golem code into python

### ISSUE THREAD

**Issue by techsbone** [golemhq/golem-tests#2]
Hi,
I need to perform other integrations with web automation, is there any way that I can run the Golem code for UI automation, from my PyCharm environment?

**Comment by luciano-renzi** [comment]
I found a way to run from Pycharm, it's not pretty but it works and the debugger works as well.

This is for Pycharm 2018.3
![image](https://user-images.githubusercontent.com/2257588/49693606-4a78f380-fb56-11e8-8b13-a143b1539555.png)

You can fill in Parameters with project, suite etc or leave empty and fill them in each time you run.
