### ISSUE TITLE
How can I read the label or button text on the UI?

### ISSUE THREAD

**Issue by techsbone** [golemhq/golem-tests#4]
Lets I need to read any particular label text from UI.

Meaning, what is an alternative here to the command **Element.getText()** from Selenium Web Driver.

**Comment by vietch2612** [comment]
Same question. Actually, I know how to read the label by using `element.text` but I don't know how to store to data in the test step 💃

**Comment by luciano-renzi** [comment]
Stale, closing.

Please use the gitter channel for questions
